image: node:latest

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
    - node_modules/  

staging:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install -D
  script:
    - serverless deploy --stage staging --verbose
  only:
    - master
    - tags
  environment: staging
